### ISSUE TITLE
@2x or @3x

### ISSUE THREAD

**Issue by RebelDesigner** [jondot/blade#5]
I really enjoy blade. Really like it because it's easy to create a build phase and have everything run automatically, never worry about that stuff anymore.

Though, I do have a question. When I supply an @3x image, this is what my result looks like:
![screenshot 2015-10-07 10 17 29](https://cloud.githubusercontent.com/assets/2981219/10332300/a56c5658-6cdc-11e5-83db-30b5843c3634.png)
As you can see, it seems that the @3x image is used as an @2x image. This can be a misunderstanding on my side, but I would expect that I have to supply the biggest possible image.

Also, I learned that it's best practice to design @1x images using vector formats. When slicing you just slice everything and than resize your canvas @2x and @3x to make sure you don't get "half pixels" with the @1x images. I know it has been suggested here, but it might be a useful addition to support one (or more vector formats). Those vector files would be the @1x images, and then automate the steps described above.

**Comment by jondot** [comment]
Regarding the first issue - try to look in finder and find out the exact dimensions of the 3x image, it might be that only Xcode is showing it that way.
Regarding the 1x recommendation - that's true, however with Blade the use case is regarding a workflow that is not dealing with vector, for example:

If in the past designers used to ship every size factor for imagesets and iconsets to developers (that they resized using sketch, photoshop, or one of their plugins), they now only need to deliver 1 size of the photo - still raster (nonvector), to the developer. From there, Blade will do the cutting of different sizes.

If you're used to working with vector - i believe you should keep doing that, it might be better for your workflow. but you would still have an issue of app icon, where you can't work in vectors. See the previous  discussion in #4 

Let me know if this make sense

**Comment by RebelDesigner** [comment]
```
FeedIcon@3x-universal-23@3x.png    => 207 x 207
FeedIcon@2x.png                    => 92 x 92
FeedIcon.png                       => 23 x 23
Original FeedIcon@3x               => 69 x 69
```

Bladefile
```
  - source: images/FeedIcon@3x.png
    mount: Shoppd/Images.xcassets/FeedIcon.imageset
    contents: true
```

**Comment by jondot** [comment]
So a few things,
- If you start from scratch (meaning FeedIcon is empty and has no images), then blade will generate all images from scratch.
- if you point blade at an existing, let's say partly-filled imageset, it will not override/destroy the images that already exist, and it will try to produce an image that matches the size of the old image that existed there.

So is there a chance that this might be a case of your FeedIcon imageset that was partly filled before you've introduced Blade?

**Comment by RebelDesigner** [comment]
That was indeed the problem. Thanks, working great now!

**Comment by RebelDesigner** [comment]
Well, now it's back to where it started. When I re-ran het project, the blade process built the files again and reworked the resolution. Same resolution files as reported in previous comments.

**Comment by jondot** [comment]
If the file names are the same, then it means that Contents.json is still there - did you try creating the FeedIcon imageset from scratch?

**Comment by RebelDesigner** [comment]
Yes. Deleted everything and then had blade recreate it..

**Comment by jondot** [comment]
Strange, here is an example output from a  typical imageset, you can see that the file names has a specific pattern:
```
-rw-r--r--  1 Dotan  staff   497B Sep 29 23:07 Contents.json
-rw-r--r--  1 Dotan  staff    36K Sep 29 23:07 splash-icon-universal-240@1x.png
-rw-r--r--  1 Dotan  staff   288K Sep 29 23:07 splash-icon-universal-240@2x.png
-rw-r--r--  1 Dotan  staff   774K Sep 29 23:07 splash-icon-universal-240@3x.png
```
It seems like what you've shown, every file has a completely different pattern, which hints that something isn't configured right. Any chance you can you paste the Contents.json file and the Bladefile verbatim here?

**Comment by RebelDesigner** [comment]
```
{
  "images": [
    {
      "filename": "FeedIcon-universal-23@1x.png",
      "idiom": "universal",
      "scale": "1x",
      "size": "23x23"
    },
    {
      "filename": "FeedIcon-universal-23@2x.png",
      "idiom": "universal",
      "scale": "2x",
      "size": "46x46"
    },
    {
      "filename": "FeedIcon-universal-23@3x.png",
      "idiom": "universal",
      "scale": "3x",
      "size": "69x69"
    }
  ],
  "info": {
    "author": "xcode",
    "version": 1
  }
}
```
```
blades:
  - source: images/iTunesArtwork@2x.png
    mount: Shoppd/Images.xcassets/AppIcon.appiconset
    contents: true
  - source: images/FeedIcon.png
    mount: Shoppd/Images.xcassets/FeedIcon.imageset
    contents: false
```
Both `contents: true/false` appear to do the same thing. First build on an empty imageset is working fine. Subsequent builds messes things up.

**Comment by jondot** [comment]
So the `Contents.json` you have pasted looks good. It should look OK on Xcode too, doesn't it?
As an aside, you should probably always do a `contents: true`, this means Blade generates a new Contents.json every time and not only new files.
Is it possible that the old files exist in this imageset? or some kind of process brings them back (git perhaps?)
Im still not sure what you are experiencing that is incorrect, I'm trying to re-read your first post, but so far everything you're doing looks ok

**Comment by RebelDesigner** [comment]
I did what you said: `contents: true` and delete all files in the imageset, also checking if the files were deleted in Finder as well. Same result.
I'll try to explain it as clear as possible, sorry for my previous, messy explanations.
First build: images created, everything OK as it should be (correct sizes and correct `Contents.json`).
Second build: images recreated, different sizes, as if the original resolutions as scaled up again, `Contents.json` still correct.

Build phases rule:
Shell: /bin.sh
./blade

./blade is the binary from the latest release located in the root of the project (same as .xcodeproj file).

**Comment by jondot** [comment]
I see, this is very strange. Can you try to use the demo project to reproduce? I don't think this is ever happened. The demo project is here, should be 5 minutes to test out:
https://github.com/jondot/blade-sample

**Comment by RebelDesigner** [comment]
Same thing happens with the sample project.
I created a new imageset and added the image to the bladefile. AppIcon seems fine.

**Comment by jondot** [comment]
Hold on, I'm recording a video of myself using blade on the sample project, including an image set. Maybe the steps are different.

**Comment by jondot** [comment]
Take a look at this, see if anything here looks different:
https://youtu.be/fX1KEquUH-o

**Comment by RebelDesigner** [comment]
https://youtu.be/U72jlWlLve0
Somewhat the same steps we take. So this is some weird behaviour. Could be my settings, but the demo project has the same problem.

https://dl.dropboxusercontent.com/u/59237165/blade-sample-with_buildstep.zip
That's the project with my settings. Maybe try and run this on your system and hopefully you'll be able to reproduce the problem. Might help figuring out what is going on..

**Comment by jondot** [comment]
Good news! I'm able to reproduce. Initial examination showed nothing, I'm not yet sure if this is the project setup or a glitch in blade, so I'm going to go a bit deeper. Hope I have results today or tomorrow!

**Comment by RebelDesigner** [comment]
Me neither. But I know for sure that I was able to reproduce it in both my normal project and the demo project. So it's not something in the project settings, I think. It must be either the bladefile config (not likely, there is not a lot in there), the image file(s) itself or a real glitch. Maybe tomorrow I would be able to examine everything and maybe help with finding a solution. Never worked with Go, but I'm sure that won't be a problem.

**Comment by jondot** [comment]
Yep, I think I have initial theory, and it is in the "size" property. So the direction now is in a size conversion glitch within Contents.json

**Comment by jondot** [comment]
Should be good now - see commit message above :) . Can you try the latest build? (either from Homebrew or releases on this repo)

**Comment by RebelDesigner** [comment]
Working great now!
Thanks for fixing it. This is making my life so much easier..

**Comment by jondot** [comment]
yay! :+1:
